apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "openbalena.db.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openbalena.db.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "openbalena.db.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "openbalena.db.fullname" . }}
  {{- if .Values.db.replicas }}
  replicas: {{ .Values.db.replicas }}
  {{- end }}
  {{- if .Values.db.podManagementPolicy }}
  podManagementPolicy: {{ .Values.db.podManagementPolicy }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "openbalena.db.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.db.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.db.terminationGracePeriodSeconds }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}-db
        image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
        {{- with .Values.db.ports }}
        ports:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      {{- if .Values.db.storageClassName }}
      storageClassName: {{ .Values.db.storageClassName }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.db.storage }}
